package com.asuliatech.fieldstaff

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp

private val Teal=Color(0xFF008B8C); private val Navy=Color(0xFF082849); private val Pale=Color(0xFFF3FBFB)
enum class Page { LOGIN,DASHBOARD,SCHOOL,TERMINAL,ACTIVATE,TEST,EVIDENCE,SUCCESS,OFFLINE,PROFILE }
class MainActivity:ComponentActivity(){override fun onCreate(s:Bundle?){super.onCreate(s);setContent{MaterialTheme(colorScheme=lightColorScheme(primary=Teal)){FieldStaff()}}}}
@Composable fun FieldStaff(){var p by remember{mutableStateOf(Page.LOGIN)};var school by remember{mutableStateOf("")};var term by remember{mutableStateOf("")};var imei by remember{mutableStateOf("")};var sim by remember{mutableStateOf("")};var terms by remember{mutableStateOf(listOf<String>())};when(p){
Page.LOGIN->Login{p=Page.DASHBOARD}
Page.DASHBOARD->Dashboard({p=Page.SCHOOL},{p=Page.OFFLINE},{p=Page.PROFILE})
Page.SCHOOL->Flow("New Installation",1){CardBox("School Details"){Field(school,{school=it},"Select School","DAV Public School, Patna");Field("Mr. Kumar (Warden)",{},"Contact Person");Field("9876543210",{},"Contact Number");Field("23 Sep 2026",{},"Installation Date");ButtonMain("Next"){p=Page.TERMINAL}}}
Page.TERMINAL->Flow("New Installation",2){CardBox("Terminal Details"){Field(term,{term=it},"Terminal ID","865423781203");Field(imei,{imei=it},"IMEI (Last 6 Digits)","007234");Field(sim,{sim=it},"SIM Number (Last 6 Digits)","678901");Text("Only the last 6 digits are required for IMEI and SIM.",color=Teal,style=MaterialTheme.typography.bodySmall);ButtonMain("Add & Activate Terminal"){if(term.isNotBlank())terms=terms+term;p=Page.ACTIVATE}}}
Page.ACTIVATE->Flow("New Installation",3){CardBox("Activate Terminal"){Text("Terminal ready",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Image(painterResource(R.drawable.login_school_staff),null,Modifier.fillMaxWidth().height(140.dp).clip(RoundedCornerShape(16.dp)),contentScale=ContentScale.Crop);Text("✓ Terminal Activated Successfully",color=Color(0xFF07864A),fontWeight=FontWeight.Bold);Detail("Terminal ID",term.ifBlank{"865423781203"});Detail("School",school.ifBlank{"DAV Public School"});Detail("Status","Active");ButtonMain("Physical Test Call"){p=Page.TEST}}}
Page.TEST->Flow("New Installation",4){CardBox("Physical Test Call"){Text("Do the parent call from the physical terminal.",color=Navy,fontWeight=FontWeight.Medium);Check("Parent 1 call tested");Check("Parent 2 call tested");Check("Voice clear on both sides");Check("Minimum 1–3 minute call completed");Text("Insert a student card in the terminal and call the parent.",color=Teal,style=MaterialTheme.typography.bodySmall);ButtonMain("Add Evidence"){p=Page.EVIDENCE}}}
Page.EVIDENCE->Flow("New Installation",5){CardBox("Add Evidence"){Evidence("📷  Take Photo","Terminal photo with date and time");Evidence("▶  Add Video","Short verification video");Text("📍 Location Captured (Auto)",color=Color(0xFF07864A),fontWeight=FontWeight.Bold);Text("Patna, Bihar  •  GPS and timestamp attached",style=MaterialTheme.typography.bodySmall);ButtonMain("Submit Installation"){p=Page.SUCCESS}}}
Page.SUCCESS->Flow("Submit Report",5){CardBox("Installation Report"){Text("✓",color=Color(0xFF07864A),style=MaterialTheme.typography.displayLarge);Text("Installation Report Submitted Successfully",color=Color(0xFF07864A),fontWeight=FontWeight.Bold,style=MaterialTheme.typography.titleLarge);Detail("School",school.ifBlank{"DAV Public School, Patna"});Detail("Terminals","${terms.size.coerceAtLeast(1)} activated");Detail("Evidence","Photo, video, GPS & time");ButtonMain("Back to Home"){p=Page.DASHBOARD}}}
Page.OFFLINE->PageBox("Offline Data"){Text("No Internet?\nNo Problem!",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold,color=Navy);Text("Your work is saved securely and submits automatically when internet is available.");ButtonMain("View Pending Data (2)"){}}
Page.PROFILE->PageBox("Profile & Settings"){Text("R",style=MaterialTheme.typography.displayMedium,color=Teal);Text("Rahul Kumar",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("Field Staff  •  ASL-FS-001");Detail("My Profile","");Detail("Change Password","");Detail("App Settings","");Detail("About","")}
}}
@Composable fun Login(go:()->Unit){var u by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};Box(Modifier.fillMaxSize()){Image(painterResource(R.drawable.login_school_staff),null,Modifier.fillMaxSize(),contentScale=ContentScale.Crop);Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(12.dp)){Spacer(Modifier.height(18.dp));Text("A  AsuliaTech",style=MaterialTheme.typography.headlineLarge,color=Navy,fontWeight=FontWeight.Bold);Text("Connect  |  Secure  |  Safer Students",color=Navy);Text("Field Staff App",style=MaterialTheme.typography.headlineMedium,color=Navy,fontWeight=FontWeight.Bold);Text("On-Ground Service for Safer Schools",color=Navy);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceEvenly){Feature("🛡","Install");Feature("🛠","Service");Feature("📄","Report");Feature("☎","Verify")};Card(colors=CardDefaults.cardColors(containerColor=Color.White.copy(alpha=.94f)),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Field(u,{u=it},"Username","Enter your username");OutlinedTextField(pass,{pass=it},label={Text("Password")},placeholder={Text("Enter your password")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth(),singleLine=true);ButtonMain("Login   →",go);Text("Forgot Password?",Modifier.align(Alignment.End),color=Teal)}};Text("“Real Work, Safer Students”",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold,color=Navy);Spacer(Modifier.height(210.dp))}}}
@Composable fun Dashboard(new:()->Unit,offline:()->Unit,profile:()->Unit){PageBox("Hi, Rahul"){Text("Field Staff",color=Teal);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("12","Total Visits",Color(0xFFE6F6FF));Metric("3","Pending",Color(0xFFFFF0E8))};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("8","Completed",Color(0xFFE9F9EC));Metric("1","New Installation",Color(0xFFF5ECFF))};Menu("＋","New Installation","Install & activate new terminals",new);Menu("◉","Activate Existing","Activate installed terminal",new);Menu("▣","Service Report","Report issue / resolution",new);Menu("▤","My Visits","View your reports",new);Menu("☁","Offline Data","Saved work waiting to sync",offline)}}
@Composable fun Flow(t:String,s:Int,content:@Composable ColumnScope.()->Unit){PageBox("$t  •  Step $s of 5",content)}
@Composable fun PageBox(t:String,content:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().background(Pale)){Row(Modifier.fillMaxWidth().background(Teal).padding(16.dp),verticalAlignment=Alignment.CenterVertically){Text("‹",color=Color.White,style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(end=18.dp));Text(t,color=Color.White,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp),content=content)}}
@Composable fun CardBox(t:String,content:@Composable ColumnScope.()->Unit){Card(shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Column(Modifier.fillMaxWidth().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text(t,style=MaterialTheme.typography.titleLarge,color=Navy,fontWeight=FontWeight.Bold);content()}}}
@Composable fun Field(v:String,c:(String)->Unit,l:String,h:String=""){OutlinedTextField(v,c,label={Text(l)},placeholder={Text(h)},modifier=Modifier.fillMaxWidth(),singleLine=true)}
@Composable fun ButtonMain(t:String,go:()->Unit){Button(go,Modifier.fillMaxWidth().height(52.dp),shape=RoundedCornerShape(14.dp),colors=ButtonDefaults.buttonColors(containerColor=Teal)){Text(t,style=MaterialTheme.typography.titleMedium)}}
@Composable fun Feature(i:String,t:String){Column(horizontalAlignment=Alignment.CenterHorizontally){Text(i,style=MaterialTheme.typography.headlineSmall);Text(t,color=Navy,fontWeight=FontWeight.Medium)}}
@Composable fun Metric(v:String,t:String,c:Color){Card(Modifier.weight(1f),colors=CardDefaults.cardColors(containerColor=c)){Column(Modifier.padding(14.dp)){Text(v,color=Teal,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text(t)}}}
@Composable fun Menu(i:String,t:String,sub:String,go:()->Unit){Card(onClick=go,shape=RoundedCornerShape(14.dp)){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Text(i,color=Teal,style=MaterialTheme.typography.headlineSmall,modifier=Modifier.padding(end=14.dp));Column(Modifier.weight(1f)){Text(t,fontWeight=FontWeight.Bold);Text(sub,style=MaterialTheme.typography.bodySmall)};Text("›",color=Teal,style=MaterialTheme.typography.headlineSmall)}}}
@Composable fun Detail(l:String,v:String){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(l,color=Color.Gray);Text(v,color=Navy,fontWeight=FontWeight.Medium)}}
@Composable fun Check(t:String){Text("☑  $t",color=Navy,fontWeight=FontWeight.Medium)}
@Composable fun Evidence(t:String,s:String){Card(colors=CardDefaults.cardColors(containerColor=Color(0xFFEAF8F8))){Column(Modifier.fillMaxWidth().padding(16.dp)){Text(t,color=Teal,fontWeight=FontWeight.Bold);Text(s,style=MaterialTheme.typography.bodySmall)}}}
