package com.asuliatech.fieldstaff
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp

class MainActivity: ComponentActivity(){override fun onCreate(s:Bundle?){super.onCreate(s);setContent{MaterialTheme(colorScheme=lightColorScheme(primary=Color(0xFF008C8C))){App()}}}}
@Composable fun App(){var login by remember{mutableStateOf(false)};if(!login)Login{login=true}else Install()}
@Composable fun Login(done:()->Unit){var u by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};Surface(color=Color(0xFFF4FBFB)){Column(Modifier.fillMaxSize().padding(24.dp).verticalScroll(rememberScrollState()),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(14.dp)){Spacer(Modifier.height(26.dp));Text("A  AsuliaTech",style=MaterialTheme.typography.headlineLarge,color=Color(0xFF062747));Text("Connect  |  Secure  |  Safer Students");Text("Field Staff App",style=MaterialTheme.typography.headlineMedium);Text("On-Ground Service for Safer Schools");Row(horizontalArrangement=Arrangement.spacedBy(18.dp)){Text("🛡 Install");Text("🛠 Service");Text("📄 Report");Text("☎ Verify")};Card{Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){OutlinedTextField(u,{u=it},label={Text("Username")},placeholder={Text("Enter your username")},modifier=Modifier.fillMaxWidth());OutlinedTextField(p,{p=it},label={Text("Password")},placeholder={Text("Enter your password")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());Button(onClick=done,modifier=Modifier.fillMaxWidth()){Text("Login  →")};Text("Forgot Password?",color=Color(0xFF008C8C),modifier=Modifier.align(Alignment.End))}};Spacer(Modifier.height(20.dp));Text("“Real Work, Safer Students”",style=MaterialTheme.typography.titleLarge,color=Color(0xFF006F70));Text("On-Site Support  •  Trusted by Schools  •  Real Reports")}}}
@Composable fun Install(){var step by remember{mutableStateOf(1)};var school by remember{mutableStateOf("")};var terminal by remember{mutableStateOf("")};var list by remember{mutableStateOf(listOf<String>())};Column(Modifier.fillMaxSize().padding(18.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("AsuliaTech Field Staff",style=MaterialTheme.typography.headlineSmall,color=Color(0xFF006F70));LinearProgressIndicator(progress={step/5f},modifier=Modifier.fillMaxWidth());Text("New Installation • Step "+step+" of 5");when(step){1->{Card{Column(Modifier.padding(16.dp)){Text("School Details",style=MaterialTheme.typography.titleLarge);OutlinedTextField(school,{school=it},label={Text("School name")},modifier=Modifier.fillMaxWidth());Button(onClick={step=2},enabled=school.isNotBlank()){Text("Next")}}}};2->{Card{Column(Modifier.padding(16.dp)){Text("Terminal Details",style=MaterialTheme.typography.titleLarge);OutlinedTextField(terminal,{terminal=it},label={Text("Terminal ID")},modifier=Modifier.fillMaxWidth());OutlinedTextField("",{},label={Text("IMEI last 6 digits")},modifier=Modifier.fillMaxWidth());OutlinedTextField("",{},label={Text("SIM last 6 digits")},modifier=Modifier.fillMaxWidth());Button(onClick={list=list+terminal;step=3},enabled=terminal.isNotBlank()){Text("Activate terminal")}}}};3->{Card{Column(Modifier.padding(16.dp)){Text("Activate Terminal",style=MaterialTheme.typography.titleLarge);Text("✓ Terminal activated successfully",color=Color(0xFF008C50));Button(onClick={step=4}){Text("Physical test call")}}}};4->{Card{Column(Modifier.padding(16.dp)){Text("Physical Test Call",style=MaterialTheme.typography.titleLarge);Text("Call from physical terminal, not from app");Text("☑ Parent call tested\n☑ Voice clear both sides\n☑ Evidence with GPS and time");Button(onClick={step=5}){Text("Attach photo / video")}}}};else->{Card{Column(Modifier.padding(16.dp)){Text("Installation Report",style=MaterialTheme.typography.titleLarge);Text(school+" • "+list.size+" terminal(s)");Text("✓ Submitted successfully",color=Color(0xFF008C50));Button(onClick={step=1;school="";list=emptyList()}){Text("Back to home")}}}}}}}
